---
fixtures:
  repositories:
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    rsync: https://github.com/simp/pupmod-simp-rsync
    selinux_core: https://github.com/puppetlabs/puppetlabs-selinux_core
    simp_options: https://github.com/simp/pupmod-simp-simp_options
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib:  https://github.com/simp/puppetlabs-stdlib
  symlinks:
    clamav: "#{source_dir}"
